window.esdocSearchIndex = [
  [
    "kogu/src/logic/operator.ts~and",
    "function/index.html#static-function-and",
    "<span>and</span> <span class=\"search-result-import-path\">kogu/src/logic/operator.ts</span>",
    "function"
  ],
  [
    "kogu/src/oop/assign.ts~assign",
    "function/index.html#static-function-assign",
    "<span>assign</span> <span class=\"search-result-import-path\">kogu/src/oop/assign.ts</span>",
    "function"
  ],
  [
    "kogu/src/oop/assoc.ts~assoc",
    "function/index.html#static-function-assoc",
    "<span>assoc</span> <span class=\"search-result-import-path\">kogu/src/oop/assoc.ts</span>",
    "function"
  ],
  [
    "kogu/src/math/between.ts~between",
    "function/index.html#static-function-between",
    "<span>between</span> <span class=\"search-result-import-path\">kogu/src/math/between.ts</span>",
    "function"
  ],
  [
    "kogu/src/list/access.ts~butlast",
    "function/index.html#static-function-butLast",
    "<span>butLast</span> <span class=\"search-result-import-path\">kogu/src/list/access.ts</span>",
    "function"
  ],
  [
    "kogu/src/text/case.ts~capitalize",
    "function/index.html#static-function-capitalize",
    "<span>capitalize</span> <span class=\"search-result-import-path\">kogu/src/text/case.ts</span>",
    "function"
  ],
  [
    "kogu/src/text/case.ts~caselesseq",
    "function/index.html#static-function-caselessEq",
    "<span>caselessEq</span> <span class=\"search-result-import-path\">kogu/src/text/case.ts</span>",
    "function"
  ],
  [
    "kogu/src/text/split.ts~chars",
    "function/index.html#static-function-chars",
    "<span>chars</span> <span class=\"search-result-import-path\">kogu/src/text/split.ts</span>",
    "function"
  ],
  [
    "kogu/src/text/char.ts~chr",
    "function/index.html#static-function-chr",
    "<span>chr</span> <span class=\"search-result-import-path\">kogu/src/text/char.ts</span>",
    "function"
  ],
  [
    "kogu/src/lambda/compose.ts~comp",
    "function/index.html#static-function-comp",
    "<span>comp</span> <span class=\"search-result-import-path\">kogu/src/lambda/compose.ts</span>",
    "function"
  ],
  [
    "kogu/src/lambda/constant.ts~constant",
    "function/index.html#static-function-constant",
    "<span>constant</span> <span class=\"search-result-import-path\">kogu/src/lambda/constant.ts</span>",
    "function"
  ],
  [
    "kogu/src/math/arithmetic.ts~dec",
    "function/index.html#static-function-dec",
    "<span>dec</span> <span class=\"search-result-import-path\">kogu/src/math/arithmetic.ts</span>",
    "function"
  ],
  [
    "kogu/src/math/trig.ts~degtorad",
    "function/index.html#static-function-degToRad",
    "<span>degToRad</span> <span class=\"search-result-import-path\">kogu/src/math/trig.ts</span>",
    "function"
  ],
  [
    "kogu/src/list/filter.ts~filter",
    "function/index.html#static-function-filter",
    "<span>filter</span> <span class=\"search-result-import-path\">kogu/src/list/filter.ts</span>",
    "function"
  ],
  [
    "kogu/src/list/access.ts~first",
    "function/index.html#static-function-first",
    "<span>first</span> <span class=\"search-result-import-path\">kogu/src/list/access.ts</span>",
    "function"
  ],
  [
    "kogu/src/text/case.ts~flipcase",
    "function/index.html#static-function-flipCase",
    "<span>flipCase</span> <span class=\"search-result-import-path\">kogu/src/text/case.ts</span>",
    "function"
  ],
  [
    "kogu/src/list/foldl.ts~foldl",
    "function/index.html#static-function-foldl",
    "<span>foldl</span> <span class=\"search-result-import-path\">kogu/src/list/foldl.ts</span>",
    "function"
  ],
  [
    "kogu/src/lambda/identity.ts~identity",
    "function/index.html#static-function-identity",
    "<span>identity</span> <span class=\"search-result-import-path\">kogu/src/lambda/identity.ts</span>",
    "function"
  ],
  [
    "kogu/src/math/range.ts~inrange",
    "function/index.html#static-function-inRange",
    "<span>inRange</span> <span class=\"search-result-import-path\">kogu/src/math/range.ts</span>",
    "function"
  ],
  [
    "kogu/src/math/arithmetic.ts~inc",
    "function/index.html#static-function-inc",
    "<span>inc</span> <span class=\"search-result-import-path\">kogu/src/math/arithmetic.ts</span>",
    "function"
  ],
  [
    "kogu/src/text/whitespace.ts~isblank",
    "function/index.html#static-function-isBlank",
    "<span>isBlank</span> <span class=\"search-result-import-path\">kogu/src/text/whitespace.ts</span>",
    "function"
  ],
  [
    "kogu/src/oop/isempty.ts~isempty",
    "function/index.html#static-function-isEmpty",
    "<span>isEmpty</span> <span class=\"search-result-import-path\">kogu/src/oop/isEmpty.ts</span>",
    "function"
  ],
  [
    "kogu/src/text/join.ts~join",
    "function/index.html#static-function-join",
    "<span>join</span> <span class=\"search-result-import-path\">kogu/src/text/join.ts</span>",
    "function"
  ],
  [
    "kogu/src/lambda/juxt.ts~juxt",
    "function/index.html#static-function-juxt",
    "<span>juxt</span> <span class=\"search-result-import-path\">kogu/src/lambda/juxt.ts</span>",
    "function"
  ],
  [
    "kogu/src/list/access.ts~last",
    "function/index.html#static-function-last",
    "<span>last</span> <span class=\"search-result-import-path\">kogu/src/list/access.ts</span>",
    "function"
  ],
  [
    "kogu/src/text/split.ts~lines",
    "function/index.html#static-function-lines",
    "<span>lines</span> <span class=\"search-result-import-path\">kogu/src/text/split.ts</span>",
    "function"
  ],
  [
    "kogu/src/list/map.ts~map",
    "function/index.html#static-function-map",
    "<span>map</span> <span class=\"search-result-import-path\">kogu/src/list/map.ts</span>",
    "function"
  ],
  [
    "kogu/src/math/arithmetic.ts~neg",
    "function/index.html#static-function-neg",
    "<span>neg</span> <span class=\"search-result-import-path\">kogu/src/math/arithmetic.ts</span>",
    "function"
  ],
  [
    "kogu/src/logic/negate.ts~negate",
    "function/index.html#static-function-negate",
    "<span>negate</span> <span class=\"search-result-import-path\">kogu/src/logic/negate.ts</span>",
    "function"
  ],
  [
    "kogu/src/lambda/noop.ts~noop",
    "function/index.html#static-function-noop",
    "<span>noop</span> <span class=\"search-result-import-path\">kogu/src/lambda/noop.ts</span>",
    "function"
  ],
  [
    "kogu/src/logic/operator.ts~or",
    "function/index.html#static-function-or",
    "<span>or</span> <span class=\"search-result-import-path\">kogu/src/logic/operator.ts</span>",
    "function"
  ],
  [
    "kogu/src/text/char.ts~ord",
    "function/index.html#static-function-ord",
    "<span>ord</span> <span class=\"search-result-import-path\">kogu/src/text/char.ts</span>",
    "function"
  ],
  [
    "kogu/src/list/partition.ts~partition",
    "function/index.html#static-function-partition",
    "<span>partition</span> <span class=\"search-result-import-path\">kogu/src/list/partition.ts</span>",
    "function"
  ],
  [
    "kogu/src/lambda/compose.ts~pipe",
    "function/index.html#static-function-pipe",
    "<span>pipe</span> <span class=\"search-result-import-path\">kogu/src/lambda/compose.ts</span>",
    "function"
  ],
  [
    "kogu/src/math/collect.ts~product",
    "function/index.html#static-function-product",
    "<span>product</span> <span class=\"search-result-import-path\">kogu/src/math/collect.ts</span>",
    "function"
  ],
  [
    "kogu/src/oop/prop.ts~prop",
    "function/index.html#static-function-prop",
    "<span>prop</span> <span class=\"search-result-import-path\">kogu/src/oop/prop.ts</span>",
    "function"
  ],
  [
    "kogu/src/text/query.ts~query",
    "function/index.html#static-function-query",
    "<span>query</span> <span class=\"search-result-import-path\">kogu/src/text/query.ts</span>",
    "function"
  ],
  [
    "kogu/src/math/trig.ts~radtodeg",
    "function/index.html#static-function-radToDeg",
    "<span>radToDeg</span> <span class=\"search-result-import-path\">kogu/src/math/trig.ts</span>",
    "function"
  ],
  [
    "kogu/src/math/rand.ts~rand",
    "function/index.html#static-function-rand",
    "<span>rand</span> <span class=\"search-result-import-path\">kogu/src/math/rand.ts</span>",
    "function"
  ],
  [
    "kogu/src/math/rand.ts~randint",
    "function/index.html#static-function-randInt",
    "<span>randInt</span> <span class=\"search-result-import-path\">kogu/src/math/rand.ts</span>",
    "function"
  ],
  [
    "kogu/src/math/range.ts~range",
    "function/index.html#static-function-range",
    "<span>range</span> <span class=\"search-result-import-path\">kogu/src/math/range.ts</span>",
    "function"
  ],
  [
    "kogu/src/lambda/repeatedly.ts~repeatedly",
    "function/index.html#static-function-repeatedly",
    "<span>repeatedly</span> <span class=\"search-result-import-path\">kogu/src/lambda/repeatedly.ts</span>",
    "function"
  ],
  [
    "kogu/src/list/access.ts~rest",
    "function/index.html#static-function-rest",
    "<span>rest</span> <span class=\"search-result-import-path\">kogu/src/list/access.ts</span>",
    "function"
  ],
  [
    "kogu/src/list/reverse.ts~reverse",
    "function/index.html#static-function-reverse",
    "<span>reverse</span> <span class=\"search-result-import-path\">kogu/src/list/reverse.ts</span>",
    "function"
  ],
  [
    "kogu/src/math/scale.ts~scale",
    "function/index.html#static-function-scale",
    "<span>scale</span> <span class=\"search-result-import-path\">kogu/src/math/scale.ts</span>",
    "function"
  ],
  [
    "kogu/src/list/singleton.ts~singleton",
    "function/index.html#static-function-singleton",
    "<span>singleton</span> <span class=\"search-result-import-path\">kogu/src/list/singleton.ts</span>",
    "function"
  ],
  [
    "kogu/src/text/split.ts~split",
    "function/index.html#static-function-split",
    "<span>split</span> <span class=\"search-result-import-path\">kogu/src/text/split.ts</span>",
    "function"
  ],
  [
    "kogu/src/math/arithmetic.ts~square",
    "function/index.html#static-function-square",
    "<span>square</span> <span class=\"search-result-import-path\">kogu/src/math/arithmetic.ts</span>",
    "function"
  ],
  [
    "kogu/src/math/collect.ts~sum",
    "function/index.html#static-function-sum",
    "<span>sum</span> <span class=\"search-result-import-path\">kogu/src/math/collect.ts</span>",
    "function"
  ],
  [
    "kogu/src/text/surround.ts~surround",
    "function/index.html#static-function-surround",
    "<span>surround</span> <span class=\"search-result-import-path\">kogu/src/text/surround.ts</span>",
    "function"
  ],
  [
    "kogu/src/lambda/thunk.ts~thunkf",
    "function/index.html#static-function-thunkF",
    "<span>thunkF</span> <span class=\"search-result-import-path\">kogu/src/lambda/thunk.ts</span>",
    "function"
  ],
  [
    "kogu/src/lambda/thunk.ts~thunkv",
    "function/index.html#static-function-thunkV",
    "<span>thunkV</span> <span class=\"search-result-import-path\">kogu/src/lambda/thunk.ts</span>",
    "function"
  ],
  [
    "kogu/src/text/case.ts~titlecase",
    "function/index.html#static-function-titleCase",
    "<span>titleCase</span> <span class=\"search-result-import-path\">kogu/src/text/case.ts</span>",
    "function"
  ],
  [
    "kogu/src/text/whitespace.ts~trim",
    "function/index.html#static-function-trim",
    "<span>trim</span> <span class=\"search-result-import-path\">kogu/src/text/whitespace.ts</span>",
    "function"
  ],
  [
    "kogu/src/text/trunc.ts~trunc",
    "function/index.html#static-function-trunc",
    "<span>trunc</span> <span class=\"search-result-import-path\">kogu/src/text/trunc.ts</span>",
    "function"
  ],
  [
    "kogu/src/text/join.ts~unchars",
    "function/index.html#static-function-unchars",
    "<span>unchars</span> <span class=\"search-result-import-path\">kogu/src/text/join.ts</span>",
    "function"
  ],
  [
    "kogu/src/list/uncons.ts~uncons",
    "function/index.html#static-function-uncons",
    "<span>uncons</span> <span class=\"search-result-import-path\">kogu/src/list/uncons.ts</span>",
    "function"
  ],
  [
    "kogu/src/text/join.ts~unlines",
    "function/index.html#static-function-unlines",
    "<span>unlines</span> <span class=\"search-result-import-path\">kogu/src/text/join.ts</span>",
    "function"
  ],
  [
    "kogu/src/text/join.ts~unwords",
    "function/index.html#static-function-unwords",
    "<span>unwords</span> <span class=\"search-result-import-path\">kogu/src/text/join.ts</span>",
    "function"
  ],
  [
    "kogu/src/oop/update.ts~update",
    "function/index.html#static-function-update",
    "<span>update</span> <span class=\"search-result-import-path\">kogu/src/oop/update.ts</span>",
    "function"
  ],
  [
    "kogu/src/text/split.ts~words",
    "function/index.html#static-function-words",
    "<span>words</span> <span class=\"search-result-import-path\">kogu/src/text/split.ts</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/index.ts",
    "file/src/index.ts.html",
    "src/index.ts",
    "file"
  ],
  [
    "src/lambda/compose.ts",
    "file/src/lambda/compose.ts.html",
    "src/lambda/compose.ts",
    "file"
  ],
  [
    "src/lambda/constant.ts",
    "file/src/lambda/constant.ts.html",
    "src/lambda/constant.ts",
    "file"
  ],
  [
    "src/lambda/identity.ts",
    "file/src/lambda/identity.ts.html",
    "src/lambda/identity.ts",
    "file"
  ],
  [
    "src/lambda/index.ts",
    "file/src/lambda/index.ts.html",
    "src/lambda/index.ts",
    "file"
  ],
  [
    "src/lambda/juxt.ts",
    "file/src/lambda/juxt.ts.html",
    "src/lambda/juxt.ts",
    "file"
  ],
  [
    "src/lambda/noop.ts",
    "file/src/lambda/noop.ts.html",
    "src/lambda/noop.ts",
    "file"
  ],
  [
    "src/lambda/repeatedly.ts",
    "file/src/lambda/repeatedly.ts.html",
    "src/lambda/repeatedly.ts",
    "file"
  ],
  [
    "src/lambda/thunk.ts",
    "file/src/lambda/thunk.ts.html",
    "src/lambda/thunk.ts",
    "file"
  ],
  [
    "src/lambda/types.ts",
    "file/src/lambda/types.ts.html",
    "src/lambda/types.ts",
    "file"
  ],
  [
    "src/list/access.ts",
    "file/src/list/access.ts.html",
    "src/list/access.ts",
    "file"
  ],
  [
    "src/list/filter.ts",
    "file/src/list/filter.ts.html",
    "src/list/filter.ts",
    "file"
  ],
  [
    "src/list/foldl.ts",
    "file/src/list/foldl.ts.html",
    "src/list/foldl.ts",
    "file"
  ],
  [
    "src/list/index.ts",
    "file/src/list/index.ts.html",
    "src/list/index.ts",
    "file"
  ],
  [
    "src/list/map.ts",
    "file/src/list/map.ts.html",
    "src/list/map.ts",
    "file"
  ],
  [
    "src/list/partition.ts",
    "file/src/list/partition.ts.html",
    "src/list/partition.ts",
    "file"
  ],
  [
    "src/list/reverse.ts",
    "file/src/list/reverse.ts.html",
    "src/list/reverse.ts",
    "file"
  ],
  [
    "src/list/singleton.ts",
    "file/src/list/singleton.ts.html",
    "src/list/singleton.ts",
    "file"
  ],
  [
    "src/list/uncons.ts",
    "file/src/list/uncons.ts.html",
    "src/list/uncons.ts",
    "file"
  ],
  [
    "src/logic/index.ts",
    "file/src/logic/index.ts.html",
    "src/logic/index.ts",
    "file"
  ],
  [
    "src/logic/negate.ts",
    "file/src/logic/negate.ts.html",
    "src/logic/negate.ts",
    "file"
  ],
  [
    "src/logic/operator.ts",
    "file/src/logic/operator.ts.html",
    "src/logic/operator.ts",
    "file"
  ],
  [
    "src/math/arithmetic.ts",
    "file/src/math/arithmetic.ts.html",
    "src/math/arithmetic.ts",
    "file"
  ],
  [
    "src/math/between.ts",
    "file/src/math/between.ts.html",
    "src/math/between.ts",
    "file"
  ],
  [
    "src/math/collect.ts",
    "file/src/math/collect.ts.html",
    "src/math/collect.ts",
    "file"
  ],
  [
    "src/math/index.ts",
    "file/src/math/index.ts.html",
    "src/math/index.ts",
    "file"
  ],
  [
    "src/math/rand.ts",
    "file/src/math/rand.ts.html",
    "src/math/rand.ts",
    "file"
  ],
  [
    "src/math/range.ts",
    "file/src/math/range.ts.html",
    "src/math/range.ts",
    "file"
  ],
  [
    "src/math/scale.ts",
    "file/src/math/scale.ts.html",
    "src/math/scale.ts",
    "file"
  ],
  [
    "src/math/trig.ts",
    "file/src/math/trig.ts.html",
    "src/math/trig.ts",
    "file"
  ],
  [
    "src/oop/assign.ts",
    "file/src/oop/assign.ts.html",
    "src/oop/assign.ts",
    "file"
  ],
  [
    "src/oop/assoc.ts",
    "file/src/oop/assoc.ts.html",
    "src/oop/assoc.ts",
    "file"
  ],
  [
    "src/oop/index.ts",
    "file/src/oop/index.ts.html",
    "src/oop/index.ts",
    "file"
  ],
  [
    "src/oop/isempty.ts",
    "file/src/oop/isEmpty.ts.html",
    "src/oop/isEmpty.ts",
    "file"
  ],
  [
    "src/oop/prop.ts",
    "file/src/oop/prop.ts.html",
    "src/oop/prop.ts",
    "file"
  ],
  [
    "src/oop/types.ts",
    "file/src/oop/types.ts.html",
    "src/oop/types.ts",
    "file"
  ],
  [
    "src/oop/update.ts",
    "file/src/oop/update.ts.html",
    "src/oop/update.ts",
    "file"
  ],
  [
    "src/text/case.ts",
    "file/src/text/case.ts.html",
    "src/text/case.ts",
    "file"
  ],
  [
    "src/text/char.ts",
    "file/src/text/char.ts.html",
    "src/text/char.ts",
    "file"
  ],
  [
    "src/text/index.ts",
    "file/src/text/index.ts.html",
    "src/text/index.ts",
    "file"
  ],
  [
    "src/text/join.ts",
    "file/src/text/join.ts.html",
    "src/text/join.ts",
    "file"
  ],
  [
    "src/text/query.ts",
    "file/src/text/query.ts.html",
    "src/text/query.ts",
    "file"
  ],
  [
    "src/text/split.ts",
    "file/src/text/split.ts.html",
    "src/text/split.ts",
    "file"
  ],
  [
    "src/text/surround.ts",
    "file/src/text/surround.ts.html",
    "src/text/surround.ts",
    "file"
  ],
  [
    "src/text/trunc.ts",
    "file/src/text/trunc.ts.html",
    "src/text/trunc.ts",
    "file"
  ],
  [
    "src/text/whitespace.ts",
    "file/src/text/whitespace.ts.html",
    "src/text/whitespace.ts",
    "file"
  ]
]